### ISSUE TITLE
ecdsa-sha2-nistp256 is a weak host key algorithm?

### ISSUE THREAD

**Issue by darakian** [evict/SSHScan#19]
Looking at your tool I see `ecdsa-sha2-nistp256` gets flagged as weak and I can't find a reason why. I can't find any discussion of it being a weak algorithm. Why is it flagged in your tool?

**Comment by bharathreddyc** [comment]
Can you please update your script to include the latest ciphers as per the below IETF page.
https://tools.ietf.org/id/draft-ietf-curdle-ssh-kex-sha2-09.html#rfc.section.3

`def get_output(rawlist):
	if rawlist:
		ciphers = ['3des-cbc','aes128-cbc','aes192-cbc','aes256-cbc','aes128-ctr','aes192-ctr','aes256-ctr','aes128-gcm@openssh.com','aes256-gcm@openssh.com','arcfour','arcfour128','arcfour256','blowfish-cbc','cast128-cbc','chacha20-poly1305@openssh.com']
		strong_ciphers = ['chacha20-poly1305@openssh.com','aes256-gcm@openssh.com','aes128-gcm@openssh.com','aes256-ctr','aes192-ctr','aes128-ctr']
		weak_ciphers = []
	   	macs = ['hmac-md5','hmac-md5-96','hmac-ripemd160','hmac-sha1','hmac-sha1-96','hmac-sha2-256','hmac-sha2-512','umac-64','hmac-md5-etm@openssh.com','hmac-md5-96-etm@openssh.com','hmac-ripemd160-etm@openssh.com','hmac-sha1-etm@openssh.com','hmac-sha1-96-etm@openssh.com','hmac-sha2-256-etm@openssh.com','hmac-sha2-512-etm@openssh.com','umac-64-etm@openssh.com','umac-128-etm@openssh.com']
		strong_macs = ['hmac-sha2-512-etm@openssh.com','hmac-sha2-256-etm@openssh.com','umac-128','umac-128-etm@openssh.com','hmac-sha2-512','hmac-sha2-256','umac-128@openssh.com']
		weak_macs = []
		kex = ['curve25519-sha256', 'curve25519-sha256@libssh.org','diffie-hellman-group1-sha1','diffie-hellman-group14-sha1','diffie-hellman-group-exchange-sha1','diffie-hellman-group-exchange-sha256','ecdh-sha2-nistp256','ecdh-sha2-nistp384','ecdh-sha2-nistp521','ecdsa-sha2-nistp256-cert-v01@openssh.com','ecdsa-sha2-nistp384-cert-v01@openssh.com','ecdsa-sha2-nistp521-cert-v01@openssh.com']
		strong_kex = ['curve25519-sha256', 'curve25519-sha256@libssh.org', 'diffie-hellman-group-exchange-sha256']
		weak_kex = []
		hka = ['ecdsa-sha2-nistp256-cert-v01@openssh.com','ecdsa-sha2-nistp384-cert-v01@openssh.com','ecdsa-sha2-nistp521-cert-v01@openssh.com','ssh-ed25519-cert-v01@openssh.com','ssh-rsa-cert-v01@openssh.com','ssh-dss-cert-v01@openssh.com','ssh-rsa-cert-v00@openssh.com','ssh-dss-cert-v00@openssh.com','ecdsa-sha2-nistp256','ecdsa-sha2-nistp384','ecdsa-sha2-nistp521','ssh-ed25519','ssh-rsa','ssh-dss']
		strong_hka = ['ssh-rsa-cert-v01@openssh.com','ssh-ed25519-cert-v01@openssh.com','ssh-rsa-cert-v00@openssh.com','ssh-rsa','ssh-ed25519']
		weak_hka = []
		dmacs = []`

**Comment by darakian** [comment]
I'm not actually using this tool anymore, but I'm still curious of the design choice if you'd like to comment on that.

**Comment by bharathreddyc** [comment]
The Kex algorithms (weak, strong, mac etc..) are hard coded. I would prefer it to be fetched from the openssh site if possible. 
The reference I could find of the Kex alogrithms/ciphers was an RFC link is below:
https://tools.ietf.org/id/draft-ietf-curdle-ssh-kex-sha2-09.html#rfc.section.3

**Comment by darakian** [comment]
Ok, but in that reference `ecdsa-sha2-nistp256` is listed as a `SHOULD` implement host key algorithm. Hence, it's strange to me that such a designation from the ietf would lead to a hard coding of the algorithm as `weak`.

**Comment by evict** [comment]
hiya, the reasoning was explained in a blog post which is embedded in the old source code: https://github.com/evict/SSHScan/commit/4be9a2b8f466eff16e6306c3e83633a5ab1cbb1c. 

https://stribika.github.io/2015/01/04/secure-secure-shell.html

It's not configurable, if you still wish to use it. Check config.yml
